version: '3.8'

services:
  postgreSQL:
    image: postgres:14.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bob}
      POSTGRES_DB: ${POSTGRES_DATABASE:-ft_transcendance}
      PGDATA: /data/postgres
    volumes:
    - db_postgres:/data/postgres
    restart: always
    ports:
    - 5432:5432
    networks:
    - ft_transcendence_network
    container_name : postgreSQL
    hostname: postgreSQL
    command: postgres -c stats_temp_directory=/tmp

  pgAdmin:
    image: dpage/pgadmin4:6.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tglory@student.42Lyon.fr}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-foobar}
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_SERVER_MODE: "False" # Required to have more permission in containers, but remove connection with email & password to pgAdmin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False" # If this is set to false, no one needs a "master password" to log in 
    volumes:
    - db_pgadmin:/var/lib/pgadmin
    - ./pgAdmin/servers.json:/pgadmin4/servers.json
    - ./pgAdmin/.pgpass:/pgadmin4/.pgpass
    restart: always
    ports:
    - 8080:8080
    networks:
    - ft_transcendence_network
    container_name : pgAdmin
    hostname: pgAdmin
    depends_on:
    - postgreSQL
# tricky way to set the right permissions on the file that contains the PostgreSQL database password
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/.pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/.pgpass;
      chown pgadmin /var/lib/pgadmin/.pgpass;
      /entrypoint.sh
      "

#  Api: (not tested for now)_
#    build:
#      context: .
#      dockerfile: ./requirements/api/Dockerfile --> il faut encore faire le dockerfile
#    restart: always
#    ports:
#    - 443:443
#    networks:
#    - ft_transcend_network
#    container_name : api.back
#    hostname: api.back
#    depends_on:
#    - postgreSQL
#    volumes: pas sûr de si il ya besoin de déclarer un volume ici
#
volumes:
  db_postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/db_postgres
  db_pgadmin:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/db_pgadmin

networks:
  ft_transcendence_network:
    driver: bridge
